package Main;

import com.panamahitek.ArduinoException;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import jssc.SerialPortException;

/**
 *
 * @author edgar
 */
public class Interfaz extends javax.swing.JFrame {
    private int[] codN = new int[7];
    
    public int[] ObtenerDatos(){
        int[] aux = new int[7];
        aux[0] = Integer.parseInt(D1.getText());
        aux[1] = Integer.parseInt(D2.getText());
        aux[2] = Integer.parseInt(D3.getText());
        aux[3] = Integer.parseInt(D4.getText());
        aux[4] = Integer.parseInt(D5.getText());
        aux[5] = Integer.parseInt(D6.getText());
        aux[6] = Integer.parseInt(D7.getText());
        return aux;
    }
    
    public void RellenarHamming(int[] x){
        P1.setText(String.valueOf(x[0]));
        P2.setText(String.valueOf(x[1]));
        DH1.setText(String.valueOf(x[2]));
        P3.setText(String.valueOf(x[3]));
        DH2.setText(String.valueOf(x[4]));
        DH3.setText(String.valueOf(x[5]));
        DH4.setText(String.valueOf(x[6]));
        P4.setText(String.valueOf(x[7]));
        DH5.setText(String.valueOf(x[8]));
        DH6.setText(String.valueOf(x[9]));
        DH7.setText(String.valueOf(x[10]));
    }
    
    public boolean CamposCorrectos(){
        if(D1.getText().equals("-") || D1.getText().equals("")){
            return false;
        }else if(D2.getText().equals("-") || D2.getText().equals("")){
            return false;
        }else if(D3.getText().equals("-") || D3.getText().equals("")){
            return false;
        }else if(D4.getText().equals("-") || D4.getText().equals("")){
            return false;
        }else if(D5.getText().equals("-") || D5.getText().equals("")){
            return false;
        }else if(D6.getText().equals("-") || D6.getText().equals("")){
            return false;
        }else if(D7.getText().equals("-") || D7.getText().equals("")){
            return false;
        }
        return true;
    }
    
    public Interfaz() {
        initComponents();
        ImageIcon imagen = new ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"));
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(fondo.getWidth(), fondo.getHeight(), Image.SCALE_DEFAULT));
        fondo.setIcon(icono);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        D1 = new javax.swing.JTextField();
        D2 = new javax.swing.JTextField();
        D3 = new javax.swing.JTextField();
        D4 = new javax.swing.JTextField();
        D5 = new javax.swing.JTextField();
        D6 = new javax.swing.JTextField();
        D7 = new javax.swing.JTextField();
        Button_Enviar = new javax.swing.JButton();
        Button_GenerarHamming = new javax.swing.JButton();
        P1 = new javax.swing.JTextField();
        P2 = new javax.swing.JTextField();
        DH1 = new javax.swing.JTextField();
        P3 = new javax.swing.JTextField();
        DH2 = new javax.swing.JTextField();
        DH3 = new javax.swing.JTextField();
        DH4 = new javax.swing.JTextField();
        P4 = new javax.swing.JTextField();
        DH5 = new javax.swing.JTextField();
        DH6 = new javax.swing.JTextField();
        DH7 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Comunicacíon de datos 2019-2  ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel2.setText("Codigo Hamming");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 110, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Dato");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        D1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        D1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        D1.setText("-");
        D1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                D1FocusGained(evt);
            }
        });
        D1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D1MouseClicked(evt);
            }
        });
        D1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D1ActionPerformed(evt);
            }
        });
        D1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                D1KeyTyped(evt);
            }
        });
        getContentPane().add(D1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 20, 25));
        D1.getAccessibleContext().setAccessibleName("");

        D2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        D2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        D2.setText("-");
        D2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                D2FocusGained(evt);
            }
        });
        D2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D2MouseClicked(evt);
            }
        });
        D2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D2ActionPerformed(evt);
            }
        });
        D2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                D2KeyTyped(evt);
            }
        });
        getContentPane().add(D2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 20, 25));
        D2.getAccessibleContext().setAccessibleName("");

        D3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        D3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        D3.setText("-");
        D3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                D3FocusGained(evt);
            }
        });
        D3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D3MouseClicked(evt);
            }
        });
        D3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D3ActionPerformed(evt);
            }
        });
        D3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                D3KeyTyped(evt);
            }
        });
        getContentPane().add(D3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 20, 25));
        D3.getAccessibleContext().setAccessibleName("");

        D4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        D4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        D4.setText("-");
        D4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                D4FocusGained(evt);
            }
        });
        D4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D4MouseClicked(evt);
            }
        });
        D4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D4ActionPerformed(evt);
            }
        });
        D4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                D4KeyTyped(evt);
            }
        });
        getContentPane().add(D4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 20, 25));
        D4.getAccessibleContext().setAccessibleName("");

        D5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        D5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        D5.setText("-");
        D5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                D5FocusGained(evt);
            }
        });
        D5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D5MouseClicked(evt);
            }
        });
        D5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D5ActionPerformed(evt);
            }
        });
        D5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                D5KeyTyped(evt);
            }
        });
        getContentPane().add(D5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 20, 25));
        D5.getAccessibleContext().setAccessibleName("");

        D6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        D6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        D6.setText("-");
        D6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                D6FocusGained(evt);
            }
        });
        D6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D6MouseClicked(evt);
            }
        });
        D6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                D6KeyTyped(evt);
            }
        });
        getContentPane().add(D6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 20, 25));
        D6.getAccessibleContext().setAccessibleName("");

        D7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        D7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        D7.setText("-");
        D7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                D7FocusGained(evt);
            }
        });
        D7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D7MouseClicked(evt);
            }
        });
        D7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D7ActionPerformed(evt);
            }
        });
        D7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                D7KeyTyped(evt);
            }
        });
        getContentPane().add(D7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 20, 25));
        D7.getAccessibleContext().setAccessibleName("");

        Button_Enviar.setBackground(new java.awt.Color(153, 153, 153));
        Button_Enviar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Button_Enviar.setText("Enviar");
        Button_Enviar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button_Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EnviarActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 60, 25));

        Button_GenerarHamming.setBackground(new java.awt.Color(153, 153, 153));
        Button_GenerarHamming.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Button_GenerarHamming.setText("Generar codigo Hamming");
        Button_GenerarHamming.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button_GenerarHamming.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_GenerarHammingActionPerformed(evt);
            }
        });
        getContentPane().add(Button_GenerarHamming, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 170, 25));

        P1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        P1.setForeground(new java.awt.Color(255, 51, 51));
        P1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P1.setText("-");
        P1.setFocusable(false);
        P1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P1ActionPerformed(evt);
            }
        });
        getContentPane().add(P1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 20, 25));
        P1.getAccessibleContext().setAccessibleName("");

        P2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        P2.setForeground(new java.awt.Color(255, 51, 51));
        P2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P2.setText("-");
        P2.setFocusable(false);
        getContentPane().add(P2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 20, 25));
        P2.getAccessibleContext().setAccessibleName("");

        DH1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DH1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DH1.setText("-");
        DH1.setFocusable(false);
        getContentPane().add(DH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 20, 25));
        DH1.getAccessibleContext().setAccessibleName("");

        P3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        P3.setForeground(new java.awt.Color(255, 51, 51));
        P3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P3.setText("-");
        P3.setFocusable(false);
        getContentPane().add(P3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 20, 25));
        P3.getAccessibleContext().setAccessibleName("");

        DH2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DH2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DH2.setText("-");
        DH2.setFocusable(false);
        DH2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DH2ActionPerformed(evt);
            }
        });
        getContentPane().add(DH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 20, 25));
        DH2.getAccessibleContext().setAccessibleName("");

        DH3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DH3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DH3.setText("-");
        DH3.setFocusable(false);
        getContentPane().add(DH3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 20, 25));
        DH3.getAccessibleContext().setAccessibleName("");

        DH4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DH4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DH4.setText("-");
        DH4.setFocusable(false);
        DH4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DH4ActionPerformed(evt);
            }
        });
        getContentPane().add(DH4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 20, 25));
        DH4.getAccessibleContext().setAccessibleName("");

        P4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        P4.setForeground(new java.awt.Color(255, 51, 51));
        P4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P4.setText("-");
        P4.setFocusable(false);
        P4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P4ActionPerformed(evt);
            }
        });
        getContentPane().add(P4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 20, 25));
        P4.getAccessibleContext().setAccessibleName("");

        DH5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DH5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DH5.setText("-");
        DH5.setFocusable(false);
        getContentPane().add(DH5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 20, 25));
        DH5.getAccessibleContext().setAccessibleName("");

        DH6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DH6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DH6.setText("-");
        DH6.setFocusable(false);
        getContentPane().add(DH6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 20, 25));
        DH6.getAccessibleContext().setAccessibleName("");

        DH7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DH7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DH7.setText("-");
        DH7.setFocusable(false);
        getContentPane().add(DH7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 20, 25));
        DH7.getAccessibleContext().setAccessibleName("");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText("Universidad de Lima ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 207, 28));
        jLabel6.setText("Profesor : Quiroz Villalobos , Lennin Paul");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 207, 28));
        jLabel7.setText("Sección : 502");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, -1, -1));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void D7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D7ActionPerformed

    private void D5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D5ActionPerformed

    private void D4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D4ActionPerformed

    private void D3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D3ActionPerformed

    private void D1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D1ActionPerformed
       
    }//GEN-LAST:event_D1ActionPerformed

    private void Button_GenerarHammingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_GenerarHammingActionPerformed
        if(CamposCorrectos()==false){
            JOptionPane.showMessageDialog(null, "Debe rellenar todos los campos con 1 o 0");
        }else{
            Codigos ref = new Codigos();
            int[] aux= ObtenerDatos();
            int[] codH = ref.GenerarCodigoHamming(aux);
            RellenarHamming(codH);
        }
    }//GEN-LAST:event_Button_GenerarHammingActionPerformed

    private void DH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DH2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DH2ActionPerformed

    private void P4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P4ActionPerformed

    private void Button_EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EnviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_EnviarActionPerformed

    private void P1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P1ActionPerformed
        //
    }//GEN-LAST:event_P1ActionPerformed

    private void DH4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DH4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DH4ActionPerformed

    private void D2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D2ActionPerformed

    private void D1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_D1KeyTyped
        if(D1.getText().length()==1){
            evt.consume();
        }          
        if (evt.getKeyChar() != '0' && evt.getKeyChar() != '1') {
            evt.consume();
        }
    }//GEN-LAST:event_D1KeyTyped

    private void D2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_D2KeyTyped
        if(D2.getText().length()==1){
            evt.consume();
        }          
        if (evt.getKeyChar() != '0' && evt.getKeyChar() != '1') {
            evt.consume();
        }
    }//GEN-LAST:event_D2KeyTyped

    private void D3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_D3KeyTyped
        if(D3.getText().length()==1){
            evt.consume();
        }          
        if (evt.getKeyChar() != '0' && evt.getKeyChar() != '1') {
            evt.consume();
        }
    }//GEN-LAST:event_D3KeyTyped

    private void D4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_D4KeyTyped
        if(D4.getText().length()==1){
            evt.consume();
        }          
        if (evt.getKeyChar() != '0' && evt.getKeyChar() != '1') {
            evt.consume();
        }
    }//GEN-LAST:event_D4KeyTyped

    private void D5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_D5KeyTyped
        if(D5.getText().length()==1){
            evt.consume();
        }          
        if (evt.getKeyChar() != '0' && evt.getKeyChar() != '1') {
            evt.consume();
        }
    }//GEN-LAST:event_D5KeyTyped

    private void D6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_D6KeyTyped
        if(D6.getText().length()==1){
            evt.consume();
        }          
        if (evt.getKeyChar() != '0' && evt.getKeyChar() != '1') {
            evt.consume();
        }
    }//GEN-LAST:event_D6KeyTyped

    private void D7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_D7KeyTyped
        if(D7.getText().length()==1){
            evt.consume();
        }          
        if (evt.getKeyChar() != '0' && evt.getKeyChar() != '1') {
            evt.consume();
        }
    }//GEN-LAST:event_D7KeyTyped

    private void D1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D1MouseClicked

    }//GEN-LAST:event_D1MouseClicked

    private void D2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D2MouseClicked

    }//GEN-LAST:event_D2MouseClicked

    private void D3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D3MouseClicked

    }//GEN-LAST:event_D3MouseClicked

    private void D4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D4MouseClicked

    }//GEN-LAST:event_D4MouseClicked

    private void D5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D5MouseClicked

    }//GEN-LAST:event_D5MouseClicked

    private void D6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D6MouseClicked

    }//GEN-LAST:event_D6MouseClicked

    private void D7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D7MouseClicked

    }//GEN-LAST:event_D7MouseClicked

    private void D1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_D1FocusGained
        D1.setText("");
    }//GEN-LAST:event_D1FocusGained

    private void D2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_D2FocusGained
        D2.setText("");
    }//GEN-LAST:event_D2FocusGained

    private void D3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_D3FocusGained
        D3.setText("");
    }//GEN-LAST:event_D3FocusGained

    private void D4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_D4FocusGained
        D4.setText("");
    }//GEN-LAST:event_D4FocusGained

    private void D5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_D5FocusGained
        D5.setText("");
    }//GEN-LAST:event_D5FocusGained

    private void D6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_D6FocusGained
        D6.setText("");
    }//GEN-LAST:event_D6FocusGained

    private void D7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_D7FocusGained
        D7.setText("");
    }//GEN-LAST:event_D7FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
        //Codifiacación
        Codigos ref = new Codigos();
        try {
            ref.arduino.arduinoRX("COM5", 9600, ref.listener);
        } catch (ArduinoException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SerialPortException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }            
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Enviar;
    private javax.swing.JButton Button_GenerarHamming;
    private javax.swing.JTextField D1;
    private javax.swing.JTextField D2;
    private javax.swing.JTextField D3;
    private javax.swing.JTextField D4;
    private javax.swing.JTextField D5;
    private javax.swing.JTextField D6;
    private javax.swing.JTextField D7;
    private javax.swing.JTextField DH1;
    private javax.swing.JTextField DH2;
    private javax.swing.JTextField DH3;
    private javax.swing.JTextField DH4;
    private javax.swing.JTextField DH5;
    private javax.swing.JTextField DH6;
    private javax.swing.JTextField DH7;
    private javax.swing.JTextField P1;
    private javax.swing.JTextField P2;
    private javax.swing.JTextField P3;
    private javax.swing.JTextField P4;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
